# Generated by Django 4.1 on 2022-11-02 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='阳光政务', max_length=100, verbose_name='名字')),
                ('create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('use', models.IntegerField(default=0, verbose_name='使用次数')),
            ],
            options={
                'verbose_name': '网站运营数据',
                'verbose_name_plural': '网站运营数据',
            },
        ),
    ]
