# Generated by Django 4.1 on 2022-10-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QueSub', models.CharField(default='匿名用户', max_length=50, verbose_name='反馈人')),
                ('City', models.CharField(max_length=50, verbose_name='城市')),
                ('Title', models.TextField(verbose_name='标题')),
                ('Class', models.CharField(max_length=50, verbose_name='类型')),
                ('Time', models.DateTimeField(verbose_name='提交时间')),
                ('Content', models.TextField(verbose_name='内容')),
                ('RepTime', models.DateTimeField(verbose_name='回复时间')),
                ('RepDep', models.CharField(max_length=50, verbose_name='回复部门')),
                ('RepCon', models.TextField(verbose_name='回复内容')),
                ('URL', models.CharField(max_length=100, verbose_name='来源')),
            ],
            options={
                'verbose_name': '政务信息',
                'verbose_name_plural': '政务信息',
            },
        ),
    ]
